export const SET_LOADING_STATE = '[BASE] SET_LOADING_STATE';
export const SET_FILTER_STATE = '[FILTER] SET_FILTER_STATE';
export const SET_NEXT_PAGE_STATE = '[PROPERTY] SET_NEXT_PAGE_STATE';
export const SET_CURRENT_PAGE_STATE = '[PROPERTY] SET_CURRENT_PAGE_STATE';
export const SET_PROPERTIES_STATE = '[PROPERTY] SET_PROPERTIES_STATE';
export const SET_PROPERTIES_FILTERED_STATE =
  '[PROPERTY] SET_PROPERTIES_FILTERED_STATE';
